### ISSUE TITLE
Escape Logic

### ISSUE THREAD

**Issue by AllenSeitz** [pickfifteen/lttp-tracker#7]
Currently Hyrule Castle is implemented as two squares: the main castle (3) and sewer escape (4). It should be changed to three squares: "Hyrule Castle (3)", "Sewer Escape (3)", and "Sewer Dark Room (1)". (As far as the chest numbers can ever be accurate, anyway.)

Reasons:

- Often the routing leads to leaving the dark room as a loose square. You can go to Zelda's Cell, then use any glove to get the 3 rear chests with bomb/boots.
- The sewer dark room technically requires lamp, unlike the rest of the castle or sewer chests. (And it should be dark green from the start.)
- The remaining "Sewer Escape (3)" should technically require (lamp or glove) && (bombs || boots). And it should also be dark green from the start and turn bright green when either gloves or lamp is found.

**Comment by pickfifteen** [comment]
The problem with this is the Open and Standard mode, right? Because in a Standard run, you'll get a free light cone here. Additionally, the tracker's logic always assumes you have bombs.

As of right now the map is implemented assuming Standard mode, without assuming you pick up the sword first to be as close to accurate in Open as possible. Is there a way to arrange this that would make sense for both Standard and Open?

Long-term it'd be nice to have a mode-select that includes the differences with Swordless, but that is not a project I will have time for in the near future. Implementing a small change like this would be doable but I want to make sure it's the right change.

**Comment by AllenSeitz** [comment]
Good point! I forgot about standard mode. I suppose then Hyrule Castle makes the most sense as a dungeon with 7 items, since it kind of is one. But that would be less convenient.

I guess the answer is to have separate copies of chests.js for standard, open, swordless, and maybe entrance modes. But yeah, that's a major feature.
